services:
  app:
    image: php:8.1-fpm
    container_name: symfony_app
    volumes:
      - .:/var/www/html
      - ./php.ini:/usr/local/etc/php/php.ini
    working_dir: /var/www/html
    networks:
      - symfony_network
    depends_on:
      - db
    environment:
      DATABASE_URL: "mysql://symfony_user:symfony_password@db:3306/symfony_db"
    command: >
      sh -c "
      curl -sS https://getcomposer.org/installer | php &&
      mv composer.phar /usr/local/bin/composer &&
      php /usr/local/bin/composer install &&
      php-fpm
      "

  web:
    image: nginx:latest
    container_name: symfony_web
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - app
    networks:
      - symfony_network

  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: symfony_db
      MYSQL_USER: symfony_user
      MYSQL_PASSWORD: symfony_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - symfony_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "8081:80"
    depends_on:
      - db
    networks:
      - symfony_network

networks:
  symfony_network:

volumes:
  db_data: